# Generated by Django 3.2.16 on 2023-06-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0003_clinic_dogwalkers_petcarecentre_petshops_veterinarydoctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDogwalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('walkin_time', models.TimeField(null=True)),
                ('walkout_time', models.TimeField(null=True)),
                ('b_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
                ('walker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.dogwalkers')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingdoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('Time', models.TimeField(null=True)),
                ('b_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.veterinarydoctors')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
            ],
        ),
    ]
