# Generated by Django 3.2.16 on 2023-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0005_adoptedpet_pet_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
