# Generated by Django 3.2.16 on 2023-06-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0007_alter_dogwalkers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogwalkers',
            name='status',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
