# Generated by Django 3.2.16 on 2023-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0008_alter_dogwalkers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdogwalker',
            name='workstatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
