# Generated by Django 3.2.16 on 2023-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0009_bookingdogwalker_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdogwalker',
            name='totalcharge',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
