# Generated by Django 3.2.16 on 2023-06-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0010_bookingdogwalker_totalcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdoctor',
            name='date',
        ),
        migrations.AddField(
            model_name='bookingdoctor',
            name='C',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='SetworkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(null=True)),
                ('Endtime', models.TimeField(null=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='clinicAddservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=40, null=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.clinic')),
            ],
        ),
    ]
