# Generated by Django 3.2.16 on 2023-06-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0011_auto_20230627_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdoctor',
            name='C',
        ),
        migrations.AddField(
            model_name='bookingdoctor',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
