# Generated by Django 3.2.16 on 2023-06-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0012_auto_20230627_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreAddservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=40, null=True)),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre')),
            ],
        ),
    ]
