# Generated by Django 3.2.16 on 2023-06-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0013_centreaddservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdoctor',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
