# Generated by Django 3.2.16 on 2023-06-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0014_bookingdoctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(null=True, upload_to='uploadImage'),
        ),
    ]
