# Generated by Django 3.2.16 on 2023-06-27 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0015_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
