# Generated by Django 3.2.16 on 2023-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0016_auto_20230627_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='setworkinghours',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
