# Generated by Django 3.2.16 on 2023-06-27 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0017_setworkinghours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdoctor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
