# Generated by Django 3.2.16 on 2023-06-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0020_alter_complaint_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('complainter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('complainter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre')),
            ],
        ),
    ]
