# Generated by Django 3.2.16 on 2023-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0022_complaint_walker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='uploadImage'),
        ),
        migrations.AlterField(
            model_name='bookingdoctor',
            name='status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdogwalker',
            name='workstatus',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(default='pending', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='petcarecentre',
            name='status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petshops',
            name='status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='veterinarydoctors',
            name='status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
    ]
