# Generated by Django 3.2.16 on 2023-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0023_auto_20230804_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='license_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dogwalkers',
            name='license_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petcarecentre',
            name='license_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petshops',
            name='license_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
