# Generated by Django 3.2.16 on 2023-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0024_auto_20230806_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptedpet',
            name='Status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='veterinarydoctors',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veterinarydoctors',
            name='register_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
