# Generated by Django 3.2.16 on 2023-08-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0027_alter_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCarecentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(null=True)),
                ('pet', models.CharField(max_length=40, null=True)),
                ('about', models.CharField(max_length=100, null=True)),
                ('booked_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
            ],
        ),
    ]
