# Generated by Django 3.2.16 on 2023-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0028_bookcarecentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=40, null=True),
        ),
    ]
