# Generated by Django 3.2.16 on 2023-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0029_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcarecentre',
            name='amount_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookcarecentre',
            name='days',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookcarecentre',
            name='status',
            field=models.CharField(default='booked', max_length=40, null=True),
        ),
    ]
