# Generated by Django 3.2.16 on 2023-08-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0030_auto_20230807_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarydoctors',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.clinic'),
        ),
    ]
