# Generated by Django 3.2.16 on 2023-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0032_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
