# Generated by Django 3.2.16 on 2023-08-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0034_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='petcarecentre',
            name='status',
        ),
        migrations.RemoveField(
            model_name='petshops',
            name='status',
        ),
        migrations.RemoveField(
            model_name='veterinarydoctors',
            name='status',
        ),
        migrations.AddField(
            model_name='bookcarecentre',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre'),
        ),
    ]
