# Generated by Django 3.2.16 on 2023-08-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0035_auto_20230808_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('amt', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='pending', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=40, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Complaint_clinic',
            new_name='feedback_centre',
        ),
        migrations.RenameModel(
            old_name='Complaint_walker',
            new_name='feedback_clinic',
        ),
        migrations.RenameModel(
            old_name='Complaint_centre',
            new_name='feedback_shop',
        ),
        migrations.RemoveField(
            model_name='clinicaddservices',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='setworkinghours',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='bookcarecentre',
            name='amount_day',
        ),
        migrations.RemoveField(
            model_name='bookingdoctor',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='bookingdogwalker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dogwalkers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='veterinarydoctors',
            name='email',
        ),
        migrations.RemoveField(
            model_name='veterinarydoctors',
            name='location',
        ),
        migrations.RemoveField(
            model_name='veterinarydoctors',
            name='user',
        ),
        migrations.AddField(
            model_name='centreaddservices',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='Endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dogwalkers',
            name='charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dogwalkers',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='about',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='petcarecentre',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petshops',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdoctor',
            name='status',
            field=models.CharField(default='Booked', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback_centre',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre'),
        ),
        migrations.AlterField(
            model_name='feedback_clinic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.clinic'),
        ),
        migrations.AlterField(
            model_name='feedback_shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petshops'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='AdoptedPet',
        ),
        migrations.DeleteModel(
            name='clinicAddservices',
        ),
        migrations.DeleteModel(
            name='SetworkingHours',
        ),
        migrations.AddField(
            model_name='order_pet',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
        migrations.AddField(
            model_name='feedback_walker',
            name='complainter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
        migrations.AddField(
            model_name='feedback_walker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.dogwalkers'),
        ),
        migrations.AddField(
            model_name='cart_pet',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.order_pet'),
        ),
        migrations.AddField(
            model_name='cart_pet',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.pet'),
        ),
    ]
