# Generated by Django 3.2.16 on 2023-08-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0036_auto_20230813_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_centre',
            old_name='complaint',
            new_name='feedbackomplaint',
        ),
        migrations.RenameField(
            model_name='feedback_clinic',
            old_name='complaint',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback_shop',
            old_name='complaint',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback_walker',
            old_name='complaint',
            new_name='feedback',
        ),
    ]
