# Generated by Django 3.2.16 on 2023-08-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0037_auto_20230813_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='about',
        ),
    ]
