# Generated by Django 3.2.16 on 2023-08-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0038_rename_category_product_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='walkerAddservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40, null=True)),
                ('walker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.dogwalkers')),
            ],
        ),
    ]
