# Generated by Django 3.2.16 on 2023-08-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0039_walkeraddservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_pet',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.pet'),
        ),
        migrations.DeleteModel(
            name='Cart_pet',
        ),
        migrations.DeleteModel(
            name='Order_pet',
        ),
    ]
