# Generated by Django 3.2.16 on 2023-08-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0040_auto_20230814_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pet',
        ),
        migrations.CreateModel(
            name='Order_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=40, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('amt', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='pending', max_length=40, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.order_pet')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.pet')),
            ],
        ),
    ]
