# Generated by Django 3.2.16 on 2023-08-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0041_auto_20230814_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookcentreservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('time', models.TimeField(null=True)),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer')),
            ],
        ),
    ]
