# Generated by Django 3.2.16 on 2023-08-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0042_bookcentreservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcentreservice',
            name='centre',
        ),
        migrations.AddField(
            model_name='bookcentreservice',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.centreaddservices'),
        ),
    ]
