# Generated by Django 3.2.16 on 2023-08-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0043_auto_20230814_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcarecentre',
            name='amount_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookcarecentre',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
