# Generated by Django 3.2.16 on 2023-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0044_auto_20230815_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcarecentre',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
