# Generated by Django 3.2.16 on 2023-08-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0045_alter_bookcarecentre_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcentreservice',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre'),
        ),
    ]
