# Generated by Django 3.2.16 on 2023-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0046_bookcentreservice_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcentreservice',
            name='status',
            field=models.CharField(default='booked', max_length=40, null=True),
        ),
    ]
