# Generated by Django 3.2.16 on 2023-08-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0047_bookcentreservice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_centre',
            name='complainter',
        ),
        migrations.RemoveField(
            model_name='feedback_clinic',
            name='complainter',
        ),
        migrations.RemoveField(
            model_name='feedback_shop',
            name='complainter',
        ),
        migrations.RemoveField(
            model_name='feedback_walker',
            name='complainter',
        ),
        migrations.AddField(
            model_name='feedback_centre',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petcarecentre'),
        ),
        migrations.AddField(
            model_name='feedback_clinic',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.clinic'),
        ),
        migrations.AddField(
            model_name='feedback_shop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.petshops'),
        ),
        migrations.AddField(
            model_name='feedback_walker',
            name='walker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.dogwalkers'),
        ),
        migrations.AlterField(
            model_name='feedback_centre',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
        migrations.AlterField(
            model_name='feedback_clinic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
        migrations.AlterField(
            model_name='feedback_shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
        migrations.AlterField(
            model_name='feedback_walker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
    ]
