# Generated by Django 3.2.16 on 2023-08-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0048_auto_20230817_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_centre',
            old_name='feedbackomplaint',
            new_name='feedback',
        ),
    ]
