# Generated by Django 3.2.16 on 2023-08-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0049_rename_feedbackomplaint_feedback_centre_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='requested', max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order_pet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='stock',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(default='available', max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Cart_pet',
        ),
        migrations.DeleteModel(
            name='Order_pet',
        ),
        migrations.AddField(
            model_name='adoption',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.pet'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.customer'),
        ),
    ]
