# Generated by Django 4.2.3 on 2026-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0050_auto_20230817_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkeraddservices',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
