# Generated by Django 5.2.9 on 2026-04-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvetapp', '0051_walkeraddservices_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdogwalker',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petvetapp.walkeraddservices'),
        ),
    ]
