"""petvet URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from petvetapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('login/',views.login),
    path('cus_register/',views.customer_Register),
    path('adminHome/',views.adminHome),
    path('clinic_reg/',views.clinic_register),
    path('carecentre_reg/',views.carecentre_register),
    path('shops_reg/',views.petshop_register),
    path('dogwalker_reg/',views.dogwalker_register),
    path('doctor_reg/',views.doctor_register),
    path('userHome/',views.userHome),
    path('carecentreHome/',views.carecentreHome),
    path('clinicHome/',views.clinicHome),
    path('shopHome/',views.shopHome),
    path('dogwalkerHome/',views.dogwalkerHome),
    path('userview_clinic/',views.userview_clinics),
    path('userview_dogwalkers/',views.userview_dogwalkers),
    path('userview_centre/',views.userview_carecentre),
    path('userview_shop/',views.userview_shop),
    path('bookdoctor/',views.book_doctor),
    path('view_bookdoctor/',views.view_doctorbooking),
    path('view_dogwalker_admin/',views.view_dogwalkers_admin),
    path('view_doctor/',views.view_doctors),
    path('view_clinics_admin/',views.view_clinics_admin),
    path('view_carecentre_admin/',views.view_carecentres_admin),
    path('view_petshop_admin/',views.view_petshops_admin),
    path('view_customer_admin/',views.view_customer_admin),
    path('addpets/',views.add_pets),
    path('addproducts/',views.add_products),
    path('viewpets_user/',views.view_pets_user),
    path('viewproducts_user/',views.view_products_user),
    path('complaint_D/',views.complaint_Doctor),
    path('viewcomplaint/',views.viewcomplaint),
    path('bookDogwalker/',views.book_dogwalkers),
    path('view_bookDogwalker/',views.view_walkerbooking),
    path('Approveclinic/',views.approveclinic),
    path('Approveshop/',views.approveshops),
    path('Approvedogwalker/',views.approvedogwalker),
    path('Approvecentre/',views.approvecentre),
    path('AdoptPet/',views.Adopt_pet),
    path('Acceptwalk/',views.dogwalker_accept),
    path('completewalk/',views.completewalk),
    path('view_userpurchase/',views.viewpurchasedproducts),
    path('view_Dogwalkerbookingdetail/',views.viewwalkerbooking_user),
    path('viewadoptedlist/',views.viewadoptedpet),
    path('viewpetlist/',views.viewpetlist_shop),
    path('Updatepet/',views.Updatepet),
    path('Deletepet/',views.DeletePet),
    path('addservice_walker/',views.Addservice),
    path('viewaddservice_walker/',views.viewaddservice),
    path('viewproduct/',views.viewproducts_shop),
    path('Updateproduct/',views.Updateproduct),
    path('Deleteproduct/',views.DeleteProduct), 
    path('addservice_centre/',views.Addservice_centre),
    path('viewaddservice_centre/',views.viewaddservice_centre),
    path('viewdoctorbooking_user/',views.viewDoctorbookingdetails_user),
    path('viewservicebooking_centre/',views.viewbookedservice),
    path('Acceptbook/',views.doctor_accept),
    path('Rejectbook/',views.doctor_reject), 
    path('complaint/',views.addcomplaint),
    path('feedback_clinic/',views.feedback_clinics),
    path('feedback_walker/',views.feedback_walkers),
    path('feedback_centre/',views.feedback_care),
    path('feedback_shop/',views.feedback_shops),
    path('delete_doctor/',views.Delete_doctor),
    path('delete_user/',views.Delete_user),
    path('delete_clinic/',views.Delete_clinic),
    path('delete_centre/',views.Delete_centre),
    path('delete_shop/',views.Delete_shop),
    path('delete_walker/',views.Delete_walkers),
    path('Updateservice_centre/',views.updateaddservice_centre),
    path('Deleteservice_centre/',views.Deleteservice_centre),
    path('clinic_detail/',views.clinic_details),
    path('centre_detail/',views.centre_services),
    path('viewadoption/',views.viewadoption),
    path('bookcentreservice/',views.book_centreservice),
    path('viewcart/',views.viewcart),
    path('removecartitem/',views.removecartitem),
    path('shelter_view/',views.userview_shelter),
    path('bookcarecentre/',views.bookcarecentre),
    path('viewbookcarecentre/',views.viewbookcarecentre),
    path('viewbookcarecentre_centre/',views.viewbookcarecentre_centre),
    path('acceptbooking_centre/',views.acceptBooking_centre),
    path('rejectbooking_centre/',views.rejectbooking_centre),
    path('makepurchase/',views.makePurchse),
    path('viewpurchase/',views.viewpurchase),
    path('viewitems/',views.ViewItems),
    path('carecentrepayment/',views.carecentrepayment),
    path('cancelcarecentrebooking/',views.cancel_carecentreBooking),
    path('viewservicebooking/',views.viewservicebookings),
    path('adoptpayment/',views.Adoptpayment),
    path('walkerbookingpayment/',views.walkerbookingpayment),
    path('servicebookingpayment/',views.servicebookingpayment),
    path('doctorbookingpayment/',views.doctorbookingpayment),
    path('canceldoctorbooking/',views.cancel_doctorBooking),
    path('cancelservicebooking/',views.cancel_serviceBooking),
    path('canceladoption/',views.cancel_Adoption),
    path('canceldogwalking/',views.cancel_dogwalking),
    path('acceptservice_centre/',views.acceptservice_centre),
    path('rejectservice_centre/',views.rejectservice_centre),
    path('viewfeedback_centre/',views.viewfeedback_centre),
    path('viewfeedback_clinic/',views.viewfeedback_clinic),
    path('viewfeedback_shop/',views.viewfeedback_shop),
    path('acceptadoption/',views.acceptadoption),
    path('rejectadoption/',views.rejectadoption),
    path('viewfeedback_walker/',views.viewfeedback_walker),
    path('viewservice_walker/',views.viewaddservice_user),
    path('shopfeedback/',views.viewshopfeedbacks),
    path('centrefeedback/',views.viewcentrefeedbacks),
    path('clinicfeedback/',views.viewclinicfeedbacks),
    path('walkerfeedback/',views.viewwalkerfeedbacks),
    path('Deleteservice/',views.Deleteservice),


]

